### ISSUE TITLE
UI Component - Todo Item

### ISSUE THREAD

**Issue by jdnichollsc** [jdnichollsc/todo-angular#4]
As a developer, I need to create a todo item component

- [x] Implement base TodoItem component
- [x] Add toggle functionality
- [x] Implement delete capability
- [x] Add past due indication
- [x] Create Storybook stories
